### ISSUE TITLE
pic

### ISSUE THREAD

**Issue by Minami0717** [Kimsukkyung0/hischool3#1]
![developer4](https://github.com/Kimsukkyung0/hischool3/assets/118950642/c09a4fe3-397f-4f26-bf79-c1c89293d6e5)
![developer7](https://github.com/Kimsukkyung0/hischool3/assets/118950642/c54f1133-7d5c-45c2-ba3b-ce78abcd3732)
![developer5](https://github.com/Kimsukkyung0/hischool3/assets/118950642/d43fdce1-5a44-49b3-9350-ad3f2bafcb04)
![developer6](https://github.com/Kimsukkyung0/hischool3/assets/118950642/eb923a6f-c367-4a46-9475-0461d6d68bf9)

**Comment by Kimsukkyung0** [comment]
??
